config/routes.rb
Rails.application.routes.draw do
  get "notifications/new"
  get "notifications/index"
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  get "admin/users/index"=>"admin/users#index"
  patch "freeze/:id"=>"admin/users#freeze", as: "user_freeze"
  patch "unfreeze/:id"=>"admin/users#unfreeze", as: "user_unfreeze"
  get "favorite_index"=>"projects#favorite_index"
    
  root :to =>"homes#top"
  get "about"=>"homes#about"
  get "search" => "searches#search"
  get "project_comments/index" => "project_comments#index"
  resources :project_comments, only: [:create, :destroy]
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create]
  resources :contacts, only: [:new, :create]
  resources :notifications
  resources :projects do
    resources :join_projects, only: [:create, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
    get "joined_user_index"=>"projects#joined_user_index"
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
    get "search_users_project" => "searches#search_users_project"
    get "joined_project_index"=>"projects#joined_project_index"
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  with_options dependent: :destroy do
    has_many :projects
    has_many :project_comments
    has_many :favorites
    has_many :relationships, class_name: "Relationship", foreign_key: "follower_id"
    has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id"
    has_many :followings, through: :relationships, source: :followed
    has_many :followers, through: :reverse_of_relationships, source: :follower
    has_many :messages
    has_many :entries
    has_many :rooms, through: :entries
  end
  
  has_one_attached :user_image

  with_options presence: true do
    validates :name
    validates :email
    validates :encrypted_password
  end
  
  def get_user_image
    (user_image.attached?) ? user_image : 'no_image.jpg'
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定　userモデルを参照する条件式に使う
  def following?(user)
    followings.include?(user)
  end

  def self.looks(word)
    @user = User.where("name LIKE?","%#{word}%")
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @users = User.all
    @users = @users.login_order(params)
    @pagenation = @users
    render "admin/users/index.html"
  end
  
  def freeze
    @user = User.find(params[:id]).update(freeze: true)
    redirect_to admin_users_index_path
  end
  
  def unfreeze
    @user = User.find(params[:id]).update(freeze: false)
    redirect_to admin_users_index_path
  end
 

  
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end
  
  protected

  #凍結されたアカウントのユーザーがログイン、ログアウトするための記述。
  def use_before_action?
    false
  end  
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :ensure_correct_user, :ensure_guest_user]
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @projects = Project.where(user_id: @user).new_order(params)
    if user_signed_in?
      @currentUserEntry = Entry.where(user_id: current_user.id)
      @userEntry = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.dmroom_id == u.dmroom_id
              @haveRoom = true
              @roomId = cu.dmroom_id
            end
          end
        end
        unless @haveRoom
          @dmroom = Dmroom.new
          @entry = Entry.new
        end
      end
    end
  end

  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報の編集に成功しました"
    else
      render "edit"
    end
  end

  def index
    @users = User.login_order(params)
    @pagenation = @users
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :user_image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    redirect_to user_path(current_user) unless @user.id == current_user.id
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_entryroom.html.erb
<% if user_signed_in? %>
  <% if user.id != current_user.id %>
    <% if @haveRoom == true %>
      <%= link_to "DMを見る/送る", room_path(roomId), class: 'btn btn-info' %>
    <% else%>
      <%= form_with model: @room, url: rooms_path do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: user.id %>
          <%= f.submit "DMを始める", class: 'btn btn-info' %>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザー情報編集</h1>
    <%= form_with model:@user do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :"ユーザー名" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
     <div class="form-group">
        <%= f.label :"ユーザーアイコン" %>
        <%= f.file_field :user_image, class: "form-control-file", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :"自己紹介" %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "編集内容を保存", class: 'btn btn-success' %>
      </div>
    <% end %>

app/views/users/index.html.erb
<h1>
  <% if current_page?(users_path) %>
    ユーザー一覧
  <% elsif  current_page?(user_followers_path(current_user)) %>
    フォロワー一覧
  <% else %>
    フォロー一覧
  <% end %>
</h1>
<div class="row">
  <table class='table border border-secondary'>
    <thead>
      <tr>
        <th></th>
        <th>ユーザー名</th>
        <th>募集件数</th>
        <th>フォロー数</th>
        <th>フォロワー数</th>
        <th>最終ログイン日時</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td>
          <%= link_to user_path(user.id) do %>
            <%= image_tag user.get_user_image, size:'50x50' %>
          <% end %>
        </td>
        <td>
          <%= link_to user_path(user.id) do %>
            <%= user.name %>
          <% end %>
        </td>
        <td>
          <%= link_to user_search_users_project_path(user.id) do %>
            <%= user.projects.count %>
          <% end %>
        </td>
        <td>
          <%= user.followings.count %>
        </td>
        <td>
          <%= user.followers.count %>
        </td>
        <td>
          <%= l user.current_sign_in_at %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'layouts/pagenate', pagenation: @pagenation %>

app/views/users/show.html.erb
<h1>ユーザー詳細
  <% if current_user == @user %>
    <%= link_to "ユーザー情報を編集する", edit_user_path(@user), class: "btn btn-success" %>
  <% end %>
</h1>
<div class="row">
  <div class="col-md-3">
    <%= image_tag @user.get_user_image, size:'200x200' %>
  </div>
  <div class="col-md-9">
    <div class="row">
      <div class="col-md-5 border">
        <h1><%= @user.name %>さん</h1>
      </div>
    </div>
    <div class"row">
      最終ログイン日時：<%= l @user.current_sign_in_at %>
    </div>
    <div class="row p-1">
      <% if user_signed_in? %>
        <% if current_user != @user %>
          <% if current_user.following?(@user) %>
            <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-danger mr-2" %>
              <% if @user.following?(current_user) %>
                <%= render "users/entryroom", user: @user, haveroom: @haveroom, roomId: @roomId %>
              <% end %>
          <% else %>
            <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<div class="row">
  <p class="mb-0">・自己紹介</p>
</div>
<div class="row ml-1">
  <div class="col-8 border pt-1 px-2">
    <%= simple_format(@user.introduction) %>
  </div>
</div>
<div class="row">
  <p> ・<%= @user.name %>さんの募集企画一覧</p>
</div>
<div class="row">
  <%= render 'projects/index', user: @user, projects: @projects%>
</div>
<div class="d-flex justify-content-center">
  <%= paginate @projects %>
</div>