config/routes.rb
Rails.application.routes.draw do
  get "notifications/new"
  get "notifications/index"
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  get "admin/users/index"=>"admin/users#index"
  patch "freeze/:id"=>"admin/users#freeze", as: "user_freeze"
  patch "unfreeze/:id"=>"admin/users#unfreeze", as: "user_unfreeze"
  get "favorite_index"=>"projects#favorite_index"
    
  root :to =>"homes#top"
  get "about"=>"homes#about"
  get "search" => "searches#search"
  get "project_comments/index" => "project_comments#index"
  resources :project_comments, only: [:create, :destroy]
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create]
  resources :contacts, only: [:new, :create]
  resources :notifications
  resources :projects do
    resources :join_projects, only: [:create, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
    get "joined_user_index"=>"projects#joined_user_index"
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
    get "search_users_project" => "searches#search_users_project"
    get "joined_project_index"=>"projects#joined_project_index"
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  
  with_options dependent: :destroy do
    has_many :project_comments
    has_many :favorites
    has_many :join_projects
  end
  
  has_one_attached :project_image
  
  with_options presence: true do
    validates :user_id
    validates :title
    validates :status
  end
  
  enum status: { draft: 0, recruiting: 1, stopped: 2, ended: 3}

  
  def get_project_image
    (project_image.attached?) ? project_image : 'top_kari.jpg'
  end
  
  def remaining_number
    capacity-join_projects.count
  end
  
  def self.looks(word,range)
    if range == "企画タイトル"
      Project.where("title LIKE?","%#{word}%")
    else
      Project.where("category LIKE?","%#{word}%")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :joined_index, :create, :edit, :update, :destroy]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :project_user?, only: [:edit, :update, :destroy]
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if params[:post]
      if @project.update(status: "recruiting")
        join_project_save
        redirect_to project_path(@project.id), notice: "企画を投稿しました！"
      else
        render "new"
      end
    else
      if @project.save
        join_project_save
        redirect_to project_path(@project.id), notice: "下書き保存しました！"
      else
        render "new"
      end
    end
  end
  
  def index
    @projects = Project.where.not(status: "draft")
    @projects = @projects.new_order(params)
    @pagenation = @projects
  end

  def favorite_index
    @favorites = Favorite.order("created_at desc").where(user_id: current_user.id).pluck(:project_id)
    @projects = Project.find(@favorites)
    pagenation_array
    render "index"
  end

  def joined_user_index
    @project = Project.find(params[:project_id]) 
    @join_users = JoinProject.where(project_id: params[:project_id]).new_order(params)
    @pagenation = @join_users
  end
  
  def joined_project_index
    @join_projects = JoinProject.order("created_at desc").where(user_id: current_user.id).pluck(:project_id)
    @projects = Project.find(@join_projects)
    pagenation_array
    render "index"
  end
  
  def show
    get_comments_list
  end

  def edit
  end
  
  def update
    if @project.update(project_params)
      redirect_to project_path(@project), notice: "企画内容を変更しました"
    else
      flash[:alert] = "変更できませんでした"
    end
  end

  def destroy
    @project.destroy
    redirect_to root_path 
  end

  private

  def project_params
    params.require(:project).permit(:title, :status, :introduction, :category, :start_time, :requirement, :capacity, :deadline, :start_time_detail, :project_image)
  end

  def set_project
    @project = Project.find(params[:id]) 
  end

  def project_user?
    redirect_to root_path if @project.user_id != current_user.id
  end

  def get_comments_list
    if admin_signed_in?
      @project_comments = ProjectComment.all 
    elsif user_signed_in?
      @project_comments = ProjectComment.where(user_id: current_user.id).or(ProjectComment.where(user_id: @project.user_id)).where(project_id: @project.id)
    end
  end

  def join_project_save
    @join = JoinProject.create(user_id: current_user.id,project_id: @project.id, status: "permission" )
  end
#ページメソッドを配列に適用させるための記述
  def pagenation_array
    projects_array = @projects.map(&:id)
    @pagenation = Kaminari.paginate_array(projects_array).page(params[:page]).per(10)
    
  end
  
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_index.html.erb
<table class="table border border-secondary">
  <thead>
    <tr>
      <th>企画タイトル</th>
      <th>募集状況</th>
      <th>タグ</th>
      <th>いいね数</th>
      <th>募集期限</th>
      <th>募集人数(残数)</th>
      <th>最終更新日</th>
    <% if user_signed_in? %>
      <% unless current_page?(user_search_users_project_path(current_user.id)) %>
        <th>投稿ユーザー</th>
      <% end %>
      <% if current_page?(user_joined_project_index_path(current_user)) %>
        <th>取消</th>
      <% end %>
    <% end %>
    </tr>
  </thead>
  <tbody>
    <% projects.each do |project| %>
      <tr>
        <td>
          <%= link_to project_path(project.id) do %>  
            <%= project.title %>
          <% end %>
        </td>
        <td>
          <%= project.status_i18n %>
        </td>
        <td>
          <%= link_to search_path(word: project.category, range:'企画タグ') do %> 
            <%= project.category %>
          <% end %>
        </td>
        <td>
          <%= project.favorites.count %>
        </td>
        <td>
          <%= l project.deadline unless project.deadline == nil %>
        </td>
        <td>
          <%= project.capacity %>人(<%= project.remaining_number unless project.capacity == nil %>人)
        </td>
        <td>
          <%= l project.updated_at unless project.updated_at == nil %>
        </td>
        
      <% if user_signed_in? %>
        <% unless current_page?(user_search_users_project_path(current_user.id)) %>
          <td>
            <%= link_to user_path(project.user_id) do %>  
              <%= project.user.name %>
            <% end %>
          </td>
        <% end %>
        <% if current_page?(user_joined_project_index_path(current_user)) %>
          <td>
            <% if JoinProject.find_by(user_id: current_user.id, project_id: project.id).status == "applying" %>
              <%= link_to "取消", project_join_project_path(project.id, project.user.id), method: :delete, data: {confirm: "参加を本当に取り消しますか？"}, class: "btn btn-danger" %>
            <% else %>
              <p class="btn btn-secondary">取消不可</p>
            <% end %>
          </td>
        <% end %>
      <% end %>
      
      </tr>
    <% end %>
  </tbody>
</table>

app/views/projects/_join_project.html.erb
  <% if JoinProject.find_by(user_id: current_user.id, project_id: project.id) %>
    <p class="btn btn-secondary">申し込み済み</p>
  <% else %>
    <%= link_to "参加申し込みをする", project_join_projects_path(project.id), method: :POST, class: "btn btn-success" %>
  <% end %>

app/views/projects/_status.html.erb
<% if project.status == "draft" %>
  <h5 class="ml-1 btn btn-info"><%= project.status_i18n %></h5>
<% elsif project.status == "recruiting" %>
  <h5 class="ml-1 btn btn-success"><%= project.status_i18n %></h5>
<% elsif project.status == "stopped" %>
  <h5 class="ml-1 btn btn-warning"><%= project.status_i18n %></h5>  
<% else %>
  <h5 class="ml-1 btn btn-secondary"><%= project.status_i18n %></h5>  
<% end %>

app/views/projects/edit.html.erb
<div class="col-md-9">
  <h1>企画編集</h1>
  <p>※トラブル防止の為、重要な事項を変更する際には、参加者の方々へご連絡ください。</h1>
  <div>
    <%= form_with model:@project do |f| %>
      <%= render 'layouts/errors', obj: @project %>
      <div class="form-group">  
        <%= f.select :status, Project.statuses_i18n.invert %>
      </div>
      <div class="form-group">
        <%= f.label :"企画名(下書きの場合にも必須)" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"企画サムネ" %>
        <%= f.file_field :project_image, class: "form-control-file", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :"募集内容詳細" %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"募集日時(開催日初日)" %>
        <%= f.datetime_field :start_time, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"募集日時詳細(候補日など)" %>
        <%= f.text_area :start_time_detail, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"企画タグ" %>
        <%= f.text_field :category, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :"募集条件" %>
        <%= f.text_area :requirement, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"募集人数" %>
        <%= f.number_field :capacity, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"募集期限" %>
        <%= f.datetime_field :deadline, class: "form-control" %>
      </div>
      <div class="row form-group">
        <%= f.submit "情報を更新する", :name => 'post', class: 'btn btn-success ml-3' %>
        <%= link_to "募集を取り消す", project_path(@project.id), method: :delete , data: {confirm: "本当に募集を取り消しますか？"}, class: "btn btn-danger ml-2"%>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/favorite_index.html.erb
<h1>いいねを押した募集一覧</h1>
<div class="row">
  <%= render 'projects/index', projects: @projects %>
</div>
<div class="d-flex justify-content-center">
  <%= paginate @projects_page %>
</div>

app/views/projects/index.html.erb
<% if current_page?(projects_path) %>
  <h1>募集一覧（新着順)</h1>
<% elsif current_page?(user_joined_project_index_path(current_user.id)) %>  
  <h1>申し込み済みの募集一覧</h1><p>※取消不可の企画は、DMやコメントにて直接募集ユーザーに御連絡下さい。</p>
<% else %>
  <h1>いいねを押した募集一覧</h1>
<% end %>
</h1>
<div class="row">
  <%= render 'projects/index', projects: @projects %>
</div>
<% if current_page?(projects_path) || current_page?(user_joined_project_index_path(current_user.id)) %>
  <%= render 'layouts/pagenate', pagenation: @pagenation %>
<% end %>

app/views/projects/joined_project_index.html.erb
<h1>申し込み済みの募集一覧</h1><p>※取消不可の企画は、DMやコメントにて直接募集ユーザーに御連絡下さい。</p>
<div class="row">
  <%= render 'projects/index', user: @user, projects: @projects %>
</div>
<div class="d-flex justify-content-center">
  <%= paginate @projects_page %>
</div>

app/views/projects/joined_user_index.html.erb
<h1>
  <%= link_to project_path(@project) do%>
    <%= @project.title %>
  <% end %>
  への参加申し込み者一覧
</h1>
  <div class="row">
    <table class='table col-md-4 border border-secondary'>
      <thead>
        <tr>
          <th>募集人数</th>
          <th>申し込み総数</th>
          <th>参加確定数</th>
        </tr>
　    </thead>
      <tbody>
        <tr>
          <td><%= @project.capacity %>人</td>
          <td><%= @join_users.count %>人</td>
          <td><%= @join_users.where(status: "permission").count %>人</td>
        </tr>
      </tbody>
    </table>
  </div>
<div class="row">
  <table class='table col-md-8 border border-secondary '>
    <thead>
      <tr>
        <th>ユーザー名</th>
        <th>申込日時</th>
        <th>参加状況</th>
      </tr>
    </thead>
    <tbody>
      <% @join_users.each do |join| %>
      <tr>
        <td>
          <%= link_to user_path(join.user.id) do %>
            <%= join.user.name %>
          <% end %>
        </td>
        <td>
          <%= l join.created_at %>  
        </td>
        <td>
          <%= form_with model: join, url: project_join_project_path(join.project_id, join.id), method: :patch do |f| %>
            <%= f.select :status, JoinProject.statuses_i18n.invert %>
            <%= f.submit "更新", class: 'btn btn-success' %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= render 'layouts/pagenate', pagenation: @pagenation %>

app/views/projects/new.html.erb
<h1>新規企画募集</h1>
<div class="row">
  <div class="col-md-10">
    <%= form_with model:@project do |f| %>
      <%= render 'layouts/errors', obj: @project %>
      <div class="form-group">
        <%= f.label :"企画名(下書きの場合にも必須)" %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
     <div class="form-group">
        <%= f.label :"企画サムネ" %>
        <%= f.file_field :project_image, class: "form-control-file", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :"募集内容詳細" %>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"募集日時(開催日初日)" %>
        <%= f.datetime_field :start_time, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"募集日時詳細(候補日など)" %>
        <%= f.text_area :start_time_detail, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"企画タグ" %>
        <%= f.text_field :category, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :"募集条件" %>
        <%= f.text_area :requirement, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"募集人数" %>
        <%= f.number_field :capacity, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :"募集期限" %>
        <%= f.datetime_field :deadline, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit "この条件で募集する", :name => 'post', class: 'btn btn-success' %>
        <%= f.submit "下書きとして保存", :name => 'draft', class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/show.html.erb
<div class="col-md-9">
  <h1>企画内容
    <% if user_signed_in? %>
      <% if current_user.id == @project.user_id %>
        <%= link_to "企画情報を編集する", edit_project_path(@project), class: "btn btn-success" %>
        <%= link_to "申込者を確認する", project_joined_user_index_path(@project), class: "btn btn-success" %>
      <% end %>
    <% end %>
  </h1>
  <div class="row">
    <h1 class="col-md-10 border border-secondary rounded-lg"><%= @project.title %></h1>
      <div class="col-md-2">
      <% if user_signed_in? %>
        <% if current_user != @project.user %>
          <div id="favorite_buttons_<%= @project.id %>">
            <%= render "favorites/favorite_btn", project: @project %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row">
    <p><%= image_tag @project.get_project_image, class:'show-img' %></p>
  </div>
  <div class="row">
    <p><i class="fas fa-circle"></i>募集状況：</p>
      <%= render 'projects/status', project: @project %>
  </div>
  <div class="row">
    <p><i class="fas fa-circle"></i>募集ユーザー</p>
  </div>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag @project.user.get_user_image, size:'100x100' %>
    </div>
    <div class="col-md-9">
      <div class="row">
        <h1 class="border border-secondary rounded-lg"><%= @project.user.name %>さん</h1>
      </div>
      <div class"row">
        企画最終編集日：<%= l @project.updated_at %>
      </div>
    </div>
  </div>
  <div class="row">
    <p><i class="fas fa-circle"></i>企画詳細</p>
  </div>
  <div class="row border border-secondary rounded-lg pl-1">
    <p><%= safe_join(@project.introduction.split("\n"),tag(:br)) %></p>
  </div>
  <div class="row">
    <p><i class="fas fa-circle"></i>募集日時(開催日初日)</p>
  </div>
  <div class="row border border-secondary rounded-lg pl-1">
    <p><%= l @project.start_time unless @project.start_time == nil %></p> 
  </div>
  <div class="row">
    <p><i class="fas fa-circle"></i>募集日時詳細(候補日など)</p>
  </div>
  <div class="row border border-secondary rounded-lg pl-1">
    <p><%= safe_join(@project.start_time_detail.split("\n"),tag(:br)) %></p>
  </div>
  <div class="row">
    <p><i class="fas fa-circle"></i>タグ</p>
  </div>
  <div class="row pl-1">
    <% unless @project.category == nil %>
      <%= link_to @project.category, search_path(word: @project.category, range:'企画タグ'), class: "btn btn-dark"%>
    <% end %>
  </div>
  <div class="row">
    <p><i class="fas fa-circle"></i>募集条件</p>
  </div>
  <div class="row border border-secondary rounded-lg pl-1">
    <p><%= safe_join(@project.requirement.split("\n"),tag(:br)) %></p>
  </div>
  <div class="row">
    <p><i class="fas fa-circle"></i>募集人数(残り人数)</p>
  </div>
  <div class="row border border-secondary rounded-lg pl-1">
    <p><%= @project.capacity %>人(<%= @project.remaining_number unless @project.capacity == nil %>人)</p>
  </div>
  <div class="row">
    <p><i class="fas fa-circle"></i>募集期限</p>
  </div>
  <div class="row border border-secondary rounded-lg pl-1">
    <p><%= l @project.deadline unless @project.deadline == nil %>まで</p>
  </div>
  <div class="row my-1">
    <%= render 'projects/join_project', project: @project if user_signed_in?%>
  </div>
</div>
<% if user_signed_in?%>
  <h5>コメント</h5>
  <div class="row ", id="comments_list">
    <%= render "project_comments/index", project_comments: @project_comments %>
  </div>
  <div class="row", id="comment_form row">
    <%= render "project_comments/form", project: @project %>
  </div>
<% end %>