config/routes.rb
Rails.application.routes.draw do
  get "notifications/new"
  get "notifications/index"
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  get "admin/users/index"=>"admin/users#index"
  patch "freeze/:id"=>"admin/users#freeze", as: "user_freeze"
  patch "unfreeze/:id"=>"admin/users#unfreeze", as: "user_unfreeze"
  get "favorite_index"=>"projects#favorite_index"
    
  root :to =>"homes#top"
  get "about"=>"homes#about"
  get "search" => "searches#search"
  get "project_comments/index" => "project_comments#index"
  resources :project_comments, only: [:create, :destroy]
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create]
  resources :contacts, only: [:new, :create]
  resources :notifications
  resources :projects do
    resources :join_projects, only: [:create, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
    get "joined_user_index"=>"projects#joined_user_index"
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
    get "search_users_project" => "searches#search_users_project"
    get "joined_project_index"=>"projects#joined_project_index"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/contact.rb
class Contact < ApplicationRecord
  with_options presence: true do  
    validates :name
    validates :content
  end
end

app/models/dmroom.rb
class Dmroom < ApplicationRecord
    has_many :messages
    has_many :entries
    has_many :users, through: :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :dmroom
  
  validates :dmroom_id, uniqueness: { scope: :user_id }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates_uniqueness_of :project_id, scope: :user_id
 
  with_options presence: true do
    validates :user_id
    validates :project_id
  end

end

app/models/join_project.rb
class JoinProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates_uniqueness_of :project_id, scope: :user_id
  
  enum status: { applying: 0, permission: 1, disapproval: 2}
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :dmroom
  
  with_options presence: true do
    validates :message
    validates :user_id
    validates :dmroom_id
  end
  
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  
  with_options dependent: :destroy do
    has_many :project_comments
    has_many :favorites
    has_many :join_projects
  end
  
  has_one_attached :project_image
  
  with_options presence: true do
    validates :user_id
    validates :title
    validates :status
  end
  
  enum status: { draft: 0, recruiting: 1, stopped: 2, ended: 3}

  
  def get_project_image
    (project_image.attached?) ? project_image : 'top_kari.jpg'
  end
  
  def remaining_number
    capacity-join_projects.count
  end
  
  def self.looks(word,range)
    if range == "企画タイトル"
      Project.where("title LIKE?","%#{word}%")
    else
      Project.where("category LIKE?","%#{word}%")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/project_comment.rb
class ProjectComment < ApplicationRecord
    belongs_to :user
    belongs_to :project
    
  with_options presence: true do
    validates :user_id
    validates :project_id
    validates :comment
  end
    
end

app/models/projectcomment.rb
class Projectcomment < ApplicationRecord
    belongs_to :user
    belongs_to :project
    
  with_options presence: true do
    validates :user_id
    validates :project_id
    validates :comment
  end
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates_uniqueness_of :followed_id, scope: :follower_id
  
  with_options presence: true do
    validates :follower_id
    validates :followed_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  with_options dependent: :destroy do
    has_many :projects
    has_many :project_comments
    has_many :favorites
    has_many :relationships, class_name: "Relationship", foreign_key: "follower_id"
    has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id"
    has_many :followings, through: :relationships, source: :followed
    has_many :followers, through: :reverse_of_relationships, source: :follower
    has_many :messages
    has_many :entries
    has_many :rooms, through: :entries
  end
  
  has_one_attached :user_image

  with_options presence: true do
    validates :name
    validates :email
    validates :encrypted_password
  end
  
  def get_user_image
    (user_image.attached?) ? user_image : 'no_image.jpg'
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定　userモデルを参照する条件式に使う
  def following?(user)
    followings.include?(user)
  end

  def self.looks(word)
    @user = User.where("name LIKE?","%#{word}%")
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  
  def index
    @entries = current_user.entries.all
    @my_room_id = []
    @entries.each do |entry|
      @my_room_id << entry.dmroom.id
    end
    @another_entries = Entry.where(dmroom_id: @my_room_id).where.not(user_id: current_user.id).new_order(params)
    @pagenation = @another_entries
  end

  def show
    @dmroom = Dmroom.find(params[:id])
    if Entry.where(user_id: current_user.id, dmroom_id: @dmroom.id).present?
      @messages = @dmroom.messages.includes(:user).new_order(params)
      @message = Message.new
      @entries = @dmroom.entries
      @another_entry = Entry.where.not(user_id: current_user.id).find_by(dmroom_id: @dmroom.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    @dmroom = Dmroom.create
    @joinCurrentUser = Entry.create!(user_id: current_user.id, dmroom_id: @dmroom.id)
    @joinUser = Entry.create(join_room_params)
    redirect_to room_path(@dmroom.id)
  end
  
  private

  def join_room_params
      params.require(:entry).permit(:user_id, :dmroom_id).merge(dmroom_id: @dmroom.id)
  end  
  
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/_form.html.erb
  <div class="col-1"></div>
  <div class="col-10">
    <%= form_with model: message, url: messages_path, local:false, class: "form-inline mb-2" do |f| %>
      <%= f.text_area :message, class: "w-75 h-100 form-group pl-0", placeholder:"ここからメッセージを送りましょう" %>
      <%= f.hidden_field :dmroom_id, value: dmroom.id %>
      <%= f.submit "送信", class: "btn btn-success ml-1" %>
    <% end %>
  </div>

app/views/rooms/_index.html.erb
  <% if messages.present? %>
    <table class="table table-sm col-md-10">
      <tbody>
        <% messages.each do |m| %>
          <% if m.user == current_user %>
            <tr class="row justify-content-center">
              <td class="col-1">
                  <%= image_tag m.user.get_user_image, size:'50x50' %>
              </td>
              <td class="col-10">
                <%= m.user.name %><br>
                <div class="mymessage">
                <p><%= safe_join(m.message.split("\n"),tag(:br)) %></p>
                <%= l m.created_at %>
                </div>
              </td>
              <td class="col-1"></td>
            </tr>
          <% else %>
            <tr class="row justify-content-center">
              <td class="col-1"></td>
              <td class="col-10 float-right text-right">
                <%= m.user.name %><br>
                <div class="othermessage">
                <p><%= safe_join(m.message.split("\n"),tag(:br)) %></p>
                <%= l m.created_at %>
                </div>
              </td>
              <td class="col-1"><%= image_tag m.user.get_user_image, size:'50x50' %></td>
            </tr>
          <% end %>  
        <% end %>
      </tbody>
    </table>
  <% end %>

app/views/rooms/index.html.erb
<h1>DM一覧</h1>
<table class="table border border-secondary">
  <thead>
    <tr>
      <th></th>
      <th>
        DM相手
      </th>
      <th>
        最新メッセージ
      </th>
      <th>
        最終更新日
      </th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @another_entries.each do |entry| %>
      <tr>
        <td>
          <%= image_tag entry.user.get_user_image, size:"50x50" %>
        </td>
        <td>
          <%= link_to user_path(entry.user_id) do %>
            <%= entry.user.name %>
          <% end %>
        </td>
        <td>
          <%= Message.find_by(id: entry.dmroom.message_ids.last).message.truncate(13) %>
        </td>
        <td>
          <%= l Message.find_by(id: entry.dmroom.message_ids.last).created_at %>
        </td>
        <td>
          <%= link_to "DMへ", room_path(entry.dmroom_id), class: "btn btn-success"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= render 'layouts/pagenate', pagenation: @pagenation %>

app/views/rooms/show.html.erb
<div class="row">
  <h1>
    <%= link_to user_path(@another_entry.user_id) do %>
      <%= @another_entry.user.name %>
    <% end %>
    さんとのDM
  </h1>
</div>
<div class="row">
  <%= render "form", dmroom: @dmroom, message: @message %>
</div>
<div class="row", id="message">
  <%= render "index", dmroom: @dmroom,messages: @messages %>
</div>
<div class="row justify-content-center">
  <%= paginate @messages %>
</div>