config/routes.rb
Rails.application.routes.draw do
  get "notifications/new"
  get "notifications/index"
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: "user/sessions"
  }
  devise_scope :user do
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  get "admin/users/index"=>"admin/users#index"
  patch "freeze/:id"=>"admin/users#freeze", as: "user_freeze"
  patch "unfreeze/:id"=>"admin/users#unfreeze", as: "user_unfreeze"
  get "favorite_index"=>"projects#favorite_index"
    
  root :to =>"homes#top"
  get "about"=>"homes#about"
  get "search" => "searches#search"
  get "project_comments/index" => "project_comments#index"
  resources :project_comments, only: [:create, :destroy]
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create]
  resources :contacts, only: [:new, :create]
  resources :notifications
  resources :projects do
    resources :join_projects, only: [:create, :update, :destroy]
    resource :favorites, only: [:create, :destroy]
    get "joined_user_index"=>"projects#joined_user_index"
  end

  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings"
    get "followers" => "relationships#followers"
    get "search_users_project" => "searches#search_users_project"
    get "joined_project_index"=>"projects#joined_project_index"
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/contact.rb
class Contact < ApplicationRecord
  with_options presence: true do  
    validates :name
    validates :content
  end
end

app/models/dmroom.rb
class Dmroom < ApplicationRecord
    has_many :messages
    has_many :entries
    has_many :users, through: :entries
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :dmroom
  
  validates :dmroom_id, uniqueness: { scope: :user_id }

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates_uniqueness_of :project_id, scope: :user_id
 
  with_options presence: true do
    validates :user_id
    validates :project_id
  end

end

app/models/join_project.rb
class JoinProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates_uniqueness_of :project_id, scope: :user_id
  
  enum status: { applying: 0, permission: 1, disapproval: 2}
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :dmroom
  
  with_options presence: true do
    validates :message
    validates :user_id
    validates :dmroom_id
  end
  
end

app/models/notification.rb
class Notification < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  
  with_options dependent: :destroy do
    has_many :project_comments
    has_many :favorites
    has_many :join_projects
  end
  
  has_one_attached :project_image
  
  with_options presence: true do
    validates :user_id
    validates :title
    validates :status
  end
  
  enum status: { draft: 0, recruiting: 1, stopped: 2, ended: 3}

  
  def get_project_image
    (project_image.attached?) ? project_image : 'top_kari.jpg'
  end
  
  def remaining_number
    capacity-join_projects.count
  end
  
  def self.looks(word,range)
    if range == "企画タイトル"
      Project.where("title LIKE?","%#{word}%")
    else
      Project.where("category LIKE?","%#{word}%")
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
end

app/models/project_comment.rb
class ProjectComment < ApplicationRecord
    belongs_to :user
    belongs_to :project
    
  with_options presence: true do
    validates :user_id
    validates :project_id
    validates :comment
  end
    
end

app/models/projectcomment.rb
class Projectcomment < ApplicationRecord
    belongs_to :user
    belongs_to :project
    
  with_options presence: true do
    validates :user_id
    validates :project_id
    validates :comment
  end
    
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates_uniqueness_of :followed_id, scope: :follower_id
  
  with_options presence: true do
    validates :follower_id
    validates :followed_id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  with_options dependent: :destroy do
    has_many :projects
    has_many :project_comments
    has_many :favorites
    has_many :relationships, class_name: "Relationship", foreign_key: "follower_id"
    has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id"
    has_many :followings, through: :relationships, source: :followed
    has_many :followers, through: :reverse_of_relationships, source: :follower
    has_many :messages
    has_many :entries
    has_many :rooms, through: :entries
  end
  
  has_one_attached :user_image

  with_options presence: true do
    validates :name
    validates :email
    validates :encrypted_password
  end
  
  def get_user_image
    (user_image.attached?) ? user_image : 'no_image.jpg'
  end

  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end
  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  # フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  # フォローしているか判定　userモデルを参照する条件式に使う
  def following?(user)
    followings.include?(user)
  end

  def self.looks(word)
    @user = User.where("name LIKE?","%#{word}%")
  end

end

app/controllers/project_comments_controller.rb
class ProjectCommentsController < ApplicationController

  def index
    @project_comments = ProjectComment.all.new_order(params)
    @pagenation = @project_comments
  end
  
  def create
    @comment = current_user.project_comments.create(project_comment_params)
    @comment.score = Language.get_data(project_comment_params[:comment]) #google natural language APIを使用
    @comment.save
    @project = Project.find(@comment.project_id)
    get_comments_list
    render "project_comments/create.js"
  end
  
  def destroy
    @project_comment = ProjectComment.find(params[:id])
    @project = Project.find(@project_comment.project_id)
    @project_comment.destroy
    get_comments_list
    render "project_comments/destroy.js"
  end
  
  private
  
  def project_comment_params
    params.require(:project_comment).permit(:comment, :project_id, :user_id).merge(user_id: current_user.id)
  end

  def get_comments_list
    if admin_signed_in?
      @project_comments = ProjectComment.all.new_order(params)
    else
      @project_comments = ProjectComment.where(user_id: current_user.id).or(ProjectComment.where(user_id: @project.user_id)).where(project_id: @project.id)
    end
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/project_comments_helper.rb
module ProjectCommentsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/rails_helper.rb
module RailsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/project_comments/_form.html.erb
<div class="col-md-1"></div>
<div class="col-md-7">
  <%= form_with url: project_comments_path, model: ProjectComment, local: false do |f| %>
    <%= f.text_area :comment, class: "w-100" %>
    <%= f.hidden_field :project_id, value: project.id %>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/project_comments/_index.html.erb
<% project_comments.each do |project_comment| %>
  <div class="col-md-1 d-flex align-items-center">
    <%= link_to user_path(project_comment.user) do %>
      <%= image_tag project_comment.user.get_user_image, size: "50x50" %><br>
    <% end %>
  </div>
  <div class="col-md-7">
    <%= project_comment.user.name %>　
    <%= l project_comment.created_at %>
    <% if admin_signed_in? %> 
      <%= link_to project_path(project_comment.project_id) do%>
        <%= project_comment.project.title%>
      <% end %>
      コメントの感情分析スコア[
      <% if project_comment.score.to_f < -0.5 %>
        <span class="text-danger">
      <% elsif project_comment.score.to_f < 0 %>
        <span class="text-warning">
      <% else %>
        <span class="text-success">
      <% end %>
      <%= project_comment.score %></span>]<br>
    <% end %>
    <p class="border rounded-lg"><%= safe_join(project_comment.comment.split("\n"),tag(:br)) %></p>
  </div>
  <div class="col-md-2 px-0 d-flex align-items-center">
    <% if (project_comment.user == current_user) || (admin_signed_in?)%>
      <%= link_to "削除", project_comment_path(project_comment), method: :delete, data: {confirm: "コメントを削除します、よろしいですか？"}, class: "btn btn-danger pull-right ", remote: true %>
    <% end %>
  </div>
  <div class="col-md-2"></div>
<% end %>

app/views/project_comments/create.js.erb
$("#comments_list").html("<%= j(render 'project_comments/index', project_comments: @project_comments) %>");
$("textarea").val('');

app/views/project_comments/destroy.js.erb
$("#comments_list").html("<%= j(render 'project_comments/index', project_comments: @project_comments) %>");

app/views/project_comments/index.html.erb
<h1>コメント一覧</h1><p>コメントのスコアが-0.5以降は赤字、0以降は黄色、それ以外は緑色で表示しています。</p>
<div class="row", id="comments_list">
  <%= render "project_comments/index", project_comments: @project_comments %>
</div>
<%= render 'layouts/pagenate', pagenation: @pagenation %>